## Installing Necesseries

In [1]:
!pip install tensorflow_text

## Import Utils

In [2]:
from transformers import AutoTokenizer, TFMobileBertForQuestionAnswering
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

## Define Preprocessor and MobileBERT

In [3]:
tokenizer = AutoTokenizer.from_pretrained("vumichien/mobilebert-uncased-squad-v2")
model = TFMobileBertForQuestionAnswering.from_pretrained("vumichien/mobilebert-uncased-squad-v2")
preprocessor = hub.KerasLayer("https://www.kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/en-uncased-preprocess/versions/3")

All model checkpoint layers were used when initializing TFMobileBertForQuestionAnswering.

All the layers of TFMobileBertForQuestionAnswering were initialized from the model checkpoint at vumichien/mobilebert-uncased-squad-v2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFMobileBertForQuestionAnswering for predictions without further training.


## Load Dataset

In [4]:
with open('/content/drive/MyDrive/Colab Notebooks/Chatbot/dataset/health-care_qa.txt', 'r', encoding='utf-8') as file:
  dataset = file.readlines()

  questions = []
  answers = []

for line in dataset[:10000]:
  q, a = line.split('\t')
  questions.append(q)
  answers.append(a.replace('\n', ''))

## Preprocessing Dataset

In [17]:
encoder_input = tokenizer(questions, answers, padding=True, return_tensors='tf')

In [18]:
print(f"Type of 'preprocessed_data': {type(encoder_input)}")
print(f"{len(encoder_input)}")
print(f"{encoder_input}")

Type of 'preprocessed_data': <class 'transformers.tokenization_utils_base.BatchEncoding'>
3
{'input_ids': <tf.Tensor: shape=(10000, 736), dtype=int32, numpy=
array([[ 101, 2129, 2079, ...,    0,    0,    0],
       [ 101, 1045, 2018, ...,    0,    0,    0],
       [ 101, 2071, 4469, ...,    0,    0,    0],
       ...,
       [ 101, 2003, 7632, ...,    0,    0,    0],
       [ 101, 2003, 7632, ...,    0,    0,    0],
       [ 101, 2003, 2009, ...,    0,    0,    0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(10000, 736), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(10000, 736), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 

## Fine-Tune Model

In [19]:
model.summary()

Model: "tf_mobile_bert_for_question_answering"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 mobilebert (TFMobileBertMa  multiple                  24581888  
 inLayer)                                                        
                                                                 
 qa_outputs (Dense)          multiple                  1026      
                                                                 
Total params: 24582914 (93.78 MB)
Trainable params: 24582914 (93.78 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.compile(optimizer='adam')

In [22]:
model.fit(encoder_input, epochs=50)

Epoch 1/50


TypeError: ignored

## Evaluate Model

In [ ]:
# question = "Who is Cristiano Ronaldo?"
# answer = "Cristiano Ronaldo is a famous football player, he is also a legend in football world. He has a lot of trophies, but unfortunately he has no Ballon D'or trophy and never win in World Cup."

# inputs = tokenizer(question, answer, return_tensors="tf")
# outputs = model(**inputs)

# answer_start_index = int(tf.math.argmax(outputs.start_logits, axis=-1)[0])
# answer_end_index = int(tf.math.argmax(outputs.end_logits, axis=-1)[0])

In [ ]:
# import numpy as np

# predict_answer_tokens = inputs.input_ids[0, answer_start_index : answer_end_index + np.random.randint(1000)]

# for word in tokenizer.decode(predict_answer_tokens):
#   result = tokenizer.decode(predict_answer_tokens).replace("[SEP]", "")

# print(result)